-- CreateTable
CREATE TABLE "User" (
    "HODNAME" TEXT NOT NULL,
    "Password" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateIndex
CREATE UNIQUE INDEX "User_HODNAME_key" ON "User"("HODNAME");
